name: Build, lint and test with NodeJS

on:
  workflow_dispatch: # enable trigger from Web UI

permissions:
  contents: read

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    name: Build, lint and test with NodeJS job
    timeout-minutes: 5

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-node
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3    # use v3 as v4 is really slow during Post Set Up
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build with Webpack
      run: npm run build --if-present

    - name: Lint with eslint
      run: npm run eslint
      
    - name: Test with Jest
      run: npm test
